### ISSUE TITLE
As manager of the Centro Trevi and the DRIN I want events that I organize to be published through the Alpine Bits Destination Data API of the Open Data Hub in order to give more visibility to my events.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/odh-alpinebits-destination-data-server#14]
The task list are:
- [x] implement a notification system that triggers the tourism importer
- [x] implement an importer from the Mobility Ninja in the tourism DB
- [x] update the Destination Data API to publish also the events of Centro Trevi ad DRIN

**Comment by bertolla** [comment]
Sheet id for events is 1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA:1179155880,
https://mobility.api.opendatahub.testingmachine.eu/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true,tname.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA:1179155880&shownull=false&distinct=true

**Comment by RudiThoeni** [comment]
Adapted the spredsheet, Import to ODH Tourism also working, conversion to destinationdata lacks, awaiting Tiagos response

**Comment by RudiThoeni** [comment]
http://tourism.opendatahub.bz.it/api/Event/515b1173-0380-467b-b40a-700de710007c
http://tourism.opendatahub.bz.it/api/Event/7c731665-42bb-4ea0-8eb9-7deeed93217e

Destination data endpoint
https://destinationdata.alpinebits.opendatahub.bz.it/1.0/events/7c731665-42bb-4ea0-8eb9-7deeed93217e
https://destinationdata.alpinebits.opendatahub.bz.it/1.0/events/515b1173-0380-467b-b40a-700de710007c

**Comment by RudiThoeni** [comment]
Ok now working also on the Destinationdata Endpoint

TODOs:

-I inserted hardcoded Ids, because i was not sure if the spaces + special characters are causing problems
-i cannot map  every field into the actual events odh scheme
-the destinationdata endpoint has a hardcoded publisher LTS defined here we have to use the _meta: source on ODH
-I think ninja uses the google api on the address to retrieve gps point right? i splitted the address into zip + city + address and the gps point was wrong, so i let the complete address in the sheet

**Comment by RudiThoeni** [comment]
The ninja url seems not working
https://mobility.api.opendatahub.testingmachine.eu/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true,tname.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA:1179155880&shownull=false&distinct=true

https://mobility.api.opendatahub.testingmachine.eu/flat/Culture/?limit=-1&offset=0&where=sactive.eq.true,sorigin.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA&shownull=false&distinct=true

returns 404

**Comment by sseppi** [comment]
The link was wrong it was missing the v2 after the domain I post here the right links:
https://mobility.api.opendatahub.testingmachine.eu/v2/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true,tname.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA:1179155880&shownull=false&distinct=true
https://mobility.api.opendatahub.testingmachine.eu/v2/flat/Culture/?limit=-1&offset=0&where=sactive.eq.true,sorigin.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA&shownull=false&distinct=true

**Comment by RudiThoeni** [comment]
all fixed now

**Comment by sseppi** [comment]
@bertolla it seems tht the syncronization between the spreadsheet and the ninja API doen't work anymore.

**Comment by bertolla** [comment]
should all be working now in production:
https://mobility.api.opendatahub.bz.it/v2/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true,tname.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA:1179155880&shownull=false&distinct=true
https://mobility.api.opendatahub.bz.it/v2/flat/Culture/?limit=-1&offset=0&where=sactive.eq.true,sorigin.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA&shownull=false&distinct=true

**Comment by sseppi** [comment]
Fine, now the mobility part seems to work fine.
After the last upates it seems that there is something wrong with the tourism and DestinationData one:

http://tourism.opendatahub.bz.it/api/Event/30121899-0644-DRIN-SalaTest-Teatroit-0815-30121899

For example the call above returns null.
@RudiThoeni : can you please check?

**Comment by RudiThoeni** [comment]
ok will check this!
error message i get is
Could not convert string to double: -. Path 'data[0].tmetadata['30121899-1800-TreviLabIT-\nSala1-Mostrait-1800-3012'].price', line 1, position 2712.

**Comment by RudiThoeni** [comment]
the import fails because the ninja api for the field "price" delivers numbers AND strings
https://mobility.api.opendatahub.testingmachine.eu/v2/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true,tname.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA:1179155880&shownull=false&distinct=true

price: 10,
price: 10000,
AND
price: "-"

is returned in the json...... it is not good to mix datatypes... sure i can parse all as string........... I think ninja is returning what in the sheet is.....

**Comment by bertolla** [comment]
Well, it depends what somebody inputs in the spreadsheet. Garbage in garbage out. That's one of the reasons why I'm not a big fan of importing data through a spreadhseet.

**Comment by RudiThoeni** [comment]
sure, therefore i wrote "I think ninja is returning what in the sheet is....."  ;)

**Comment by bertolla** [comment]
Furthermore use the production version since I haven't deployed the test version after making a hotfix on master.
Use https://mobility.api.opendatahub.bz.it/v2/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true,tname.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA:1179155880&shownull=false&distinct=true instead

**Comment by sseppi** [comment]
> the import fails because the ninja api for the field "price" delivers numbers AND strings
> https://mobility.api.opendatahub.testingmachine.eu/v2/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true,tname.eq.1aJW6sEGo40hWeL_B2yK4N7CIGwRlmwVpAkwqxjF1ruA:1179155880&shownull=false&distinct=true
> 
> price: 10,
> price: 10000,
> AND
> price: "-"
> 
> is returned in the json...... it is not good to mix datatypes... sure i can parse all as string........... I think ninja is returning what in the sheet is.....

@RudiThoeni this means that I have to say to CEntro trevi to punt in the price field a number or leave the field empty? Is this fine for you?

**Comment by RudiThoeni** [comment]
Yes! also a date field must have a date inside

**Comment by RudiThoeni** [comment]
now it fails because a event has a place that does not exist in the list of places

7c731665-42bb-4ea0-8eb9-7deeed93217e: {
room: "Sala +1",
place: "TreviLabIT",

the place has sname "TreviLab IT"

I can ignore all this errors.... but that makes more difficult to find where its not working ;)

**Comment by sseppi** [comment]
@RudiThoeni thanks for the help.
No I think we have to keet this checks otherwise we will get even more garbedge in the data.

**Comment by RudiThoeni** [comment]
ok data should now be displayed
http://tourism.opendatahub.bz.it/api/Event/30121899-1800-TreviLabIT-Lab2-IT-Mostrait-1800-301
http://tourism.opendatahub.bz.it/api/Event/30121899-0644-DRIN-IT-Aperto2-Teatroit-0815-301218

**Comment by sseppi** [comment]
Super now it seems working!
Thanks guys!
