### ISSUE TITLE
As an AlpineBits Member I want to have the Destination Data Server Reference Implementation that exposes data coming from the Open Data Hub online.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/odh-alpinebits-destination-data-server#4]

**Comment by RudiThoeni** [comment]
deployed latest version, https://destinationdata.alpinebits.opendatahub.testingmachine.eu/
is now under basic auth (alpinebits/supersecret) if you want to get the data you have to use postman and pass the basic auth header

**Comment by sseppi** [comment]
The testing environment works now fine exept the event series. For the event series we need that also LTS provides us more information about the relationship between the single event and its event series.

Now I have two questions to the group and espetially to @RudiThoeni and @ohnewein :
- shall we publish the destination data API also on production (but the event series one) under destinatindata.opendadahub.bz.it?
- how can we motivate LTS to introduce the concept of Event Series in Tic?

**Comment by sseppi** [comment]
It has been decided to publish the reference implementation under: the following link:

destinationdata.alpinebits.opendatahub.bz.it

@RudiThoeni  can you do this?
