### ISSUE TITLE
As an Open Data Hub data consumer I want to get data through a Alpine Bits Destination Data API.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/odh-alpinebits-destination-data-server#6]
In order to publish the server we have to consider the following points:
- [x] integrate our authentication instead the basic auth of UniBZ
- [x] disable the EventSeries
- [x] create a CD/CI pipeline

The URL will be: destinationdata.alpinebits.opendatahub.bz.it

Since LTS doesn't support Event Series, for the moment we do not integrate the Event Series too. As soon LTS will implement this feature we will integrate it too.

**Comment by alexlanz** [comment]
@sseppi Should we add the same data (SQL and S3) as for the test environment by coping everything over? Or should I leave everything blank to start from scratch?

**Comment by alexlanz** [comment]
Sorry, wrong ticket! This is related to another project.

**Comment by alexlanz** [comment]
Should be ready and online now:

destinationdata.alpinebits.opendatahub.testingmachine.eu
destinationdata.alpinebits.opendatahub.bz.it
